### PR TITLE
Fix: Dimensions on small devices. Fix: Line on the far right showing

### PR DESCRIPTION
**Pull request by Karim94**
[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### PR author
Karim
#### Relevant issue tracker links  
N / A
#### Linked PRs in other repos
N / A
#### Manual testing instructions  
N / A
#### Additional notes
This is a bug fix and code style PR.
Bug #1: Fixed dimensions on small screen.
Bug #2: Fixed loading line icon on the far right was showing.

----
### Reviewer

* Localisation.
* Architectural decisions.
* Performance.
* Comments.
* Big feature tech design documentation.
* Readability.
* DRY.
* Can we extract something to SDK?
* Are there any bicycles invented that should be replaced with existing SDK
* Are there unit and e2e tests added?

----
### Repository owner

- [ ] At least one approved code review exists.
- [ ] Approved tester review exists and was done after last code changes.
- [ ] CI build and tests passed.
- [ ] This feature/bugfix is considered fully done and can get merged.
- [ ] PR name follows conventional changelog format.
- [ ] I'll remember to squash commits.

### CODE REVIEW

**Comment by Karim94** [comment]
@ebilg Ready for testing

**Comment by ebilg** [comment]
not sure what I should be testing. bugs described do not have enough detail to reproduce. please include screenshots for visual bugs

**Comment by Karim94** [comment]
@ebilg 
Bug #1: The loading screen used to be clipped on a small sreen
Bug #2: There was an unwanted icon at the far right, it should not be there now.
image

**Comment by ebilg** [comment]
might want to deal with 4" (iPhone SE) while you're working on this
screen shot 2017-11-29 at 9 22 22 am

**Comment by seavan** [comment]
Yes, probably. In any case, change the code, so that it doesn't render image if it's source is null - it's better for layout anyway

**Comment by Karim94** [comment]
@ebilg ready to re-test. I can't test it on iOS, so I don't actually know if this works, but it should :)

**Comment by seavan** [comment]
I tested, it looks good now:
image

**Comment by seavan** [comment]
@Karim94 there are conflicts to be resolved ^

**Comment by Karim94** [comment]
@seavan Conflicts resolved.

**Pull request merged**
