### PR TITLE
fix: hide options button in folder move [branch ch8631]

### PR DESCRIPTION
**Pull request by Karim94**
#### Relevant info and issue/PR links 
https://app.clubhouse.io/peerio/story/8631/mobile-remove-options-buttons-from-folder-move-view
#### Testing instructions  
Check that the button isnt there anymore

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by seavan** [comment]
@ebilg @paulrdukes we hid the options icon in the folder selection dialog. is that ok?

**Comment by paulrdukes** [comment]
@seavan what?

**Comment by Karim94** [comment]
@paulrdukes he means we hid the "..." button that was showing in the file move screen, clicking it did nothing anyways and we dont think it should be there:
image

**Comment by paulrdukes** [comment]
@Karim94 👍

**Pull request merged**
