### PR TITLE
feat: e2e test leave room and navigate to chat list [branch ch7326]

### PR DESCRIPTION
**Pull request by Karim94**
#### Relevant info and issue/PR links 
https://app.clubhouse.io/peerio/story/7326/mobile-e2e-tests-when-leaving-channel-navigate-to-chat-list
#### Testing instructions  
The test itself works. But there's a bug where leaving a room crashes the app. I will see if Eren can reproduce that and make a CH task.

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by alexandra-marin** [comment]
@Karim94 staging was reset, please add the users again.
This test doesn't need to be a scenario outline, it can be converted to a simple scenario (same for all outlines which have only one row of data).

**Comment by Karim94** [comment]
@alexandra-marin Test accounts have been re-created and the credentials were changed in internal docs. Fixed the scenario outline issue too.

**Comment by seavan** [comment]
waiting for check from @alexandra-marin to merge

**Comment by alexandra-marin** [comment]
I get this:
`✖ And I create a new room # test/code/steps/chat.js:12
       Error: An element could not be located on the page using the given search parameters ("~buttonGo").`

If it's iOS thing, I'll try to fix it myself tomorrow

**Comment by Karim94** [comment]
@alexandra-marin Please don't forget to change the task state when you make the fix

**Comment by seavan** [comment]
@Karim94 conflicts need to be fixed and tested before merge.

**Pull request merged**
