### PR TITLE
feat: remove account upgrade [ch18356]

### PR DESCRIPTION
**Pull request by seavan**
#### Relevant info and issue/PR links 

https://app.clubhouse.io/peerio/story/18356/mobile-remove-upsells-and-iap-everywhere

#### Testing instructions  

There should be no account upgrade offers in files when reaching storage limit
No account upgrade elements in the settings menu as well.

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by seavan** [comment]
@ebilg @BlueMona ready for testing

**Comment by BlueMona** [comment]
tested pending correction on CH

**Comment by seavan** [comment]
@BlueMona I've checked, the mentioned warning is from the server, not the client. if there are no more issues, this could be merged, then.

**Comment by BlueMona** [comment]
@seavan in that case:  this branch is tested and ok to merge

**Pull request merged**
