### PR TITLE
chore: upgrade mobx

### PR DESCRIPTION
**Pull request by anri-asaturov**
## task:

https://app.clubhouse.io/peerio/story/9909/mobile-update-mobx

## testing:

full regression testing.

### CODE REVIEW

**Comment by alexandra-marin** [comment]
I get this err: [mobx] 'extras' is no longer part of the public MobX api. Please consult the changelog to find out where this functionality went

**Comment by anri-asaturov** [comment]
I found one place in all 3 repos that uses mobx extras, and that's icebear e2e tests, could you grep where did you get the error?

**Comment by anri-asaturov** [comment]
@alexandra-marin ok i think it's inside mobx-react, bumped the dependency

**Comment by alexandra-marin** [comment]
Getting errors from icebear branch:

1. console.error: "[mobx] Deprecated: 'observable.shallowBox', use 'observable.box(value, { deep: false })' instead."

2. console.error: "[mobx] Deprecated: 'observable.shallowMap', use 'observable.map(values, { deep: false })' instead."

**Comment by anri-asaturov** [comment]
These are deprecation warnings, code still works, we need to resolve deprecations by the time we switch to mobx6

**Comment by alexandra-marin** [comment]
But they break the app
simulator screen shot - iphone 6 - 2018-10-10 at 19 16 58

**Comment by anri-asaturov** [comment]
made some fixes

**Comment by seavan** [comment]
@anri-asaturov it gets hysterical if there's a console.error on module requirement. checking.

**Comment by seavan** [comment]
@anri-asaturov 
almost everything works fine, except for this:
https://github.com/PeerioTechnologies/peerio-icebear/blob/mobx5/src/models/files/file-store.ts#L446

I get a lot of errors stating:

```
Error loading file from chat
TypeError: One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it...
```

image

I get it when opening a channel with inline files.

This error is present in dev as well.

**Comment by anri-asaturov** [comment]
i'm afraid this is related to cross-fetch @lostfictions

**Comment by lostfictions** [comment]
guess that pr needed testing before being merged! i can take a look on friday, but maybe someone else wants to look sooner

**Comment by seavan** [comment]
created a task and a PR for this problem separately here:
https://app.clubhouse.io/peerio/story/14573/sdk-object-assign-crashes-when-operating-with-objects-of-file-prototype

https://github.com/PeerioTechnologies/peerio-icebear/pull/328

this branch is ready for testing, no other problems here.

**Pull request merged**
