### PR TITLE
Feat chatview refactor

### PR DESCRIPTION
**Pull request by seavan**
#### Relevant info and issue/PR links 
 
https://app.clubhouse.io/peerio/story/15614/mobile-improve-scrolling-paging

#### Testing instructions  

Scroll view should remain properly positioned after paging back and forth.

Possible regressions:

- chat unread indicator
- incoming message scroll

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by seavan** [comment]
@BlueMona @ebilg ready for testing

**Comment by BlueMona** [comment]
Tested; bug to be fixed on CH.

**Comment by seavan** [comment]
@BlueMona merged with a fix on dev.
TF will be 3.430

**Comment by BlueMona** [comment]
tested and can be merged.

**Comment by seavan** [comment]
@BlueMona Anri has found a small issue with chat scrolling back if you scroll it immediately after opening. It should be fixed now. TF 3.431. Please take a quick look that it still works.

**Comment by BlueMona** [comment]
@seavan the issue observed by Anri appears to be fixed in TF 3.431 and scrolling remains in correct position. Can be merged.

**Pull request merged**
