### PR TITLE
Feat micro thumbnail file upload

### PR DESCRIPTION
**Pull request by Karim94**
#### Relevant info and issue/PR links 
https://app.clubhouse.io/peerio/story/1671/mobile-when-uploading-image-into-chat-show-progress-bar-until-image-is-ready-to-display
Uploading a non-image works correctly
Uploading an image does not display the preview at all, my guess is that it doesn't find the path correctly. I left a TODO where I suspected the issue is.
#### Testing instructions  

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by seavan** [comment]
@Karim94 please test on android, and if it works, request review again.

on an unrelated note, uploaded images do not expand automatically right now on this branch. this needs checking.

**Comment by Karim94** [comment]
@seavan it works fine, but the sizing is a bit off for some reason. See attached.
image

**Comment by seavan** [comment]
@Karim94 thumbnail is sized proportionaly in the 32x32 box
so neither dimension should exceed 32. that's why you get scaled down 32x23 image centered in the box.

on the other hand, file type icons are weird. first, they have spacing already in image files (you can see it if you open it in image editor):

image

that makes it look like the spacing between thumbnail and text is off (because there's too few spacing). you can see it by container borders here:

image

thumbnail has no spacing in the container, file type icon has a lot.

I think that's fine for now, just letting you know how is container organized.

**Comment by ebilg** [comment]
looks good!

**Comment by seavan** [comment]
@Karim94 please resolve conflicts and check that it works, then I'll merge

**Comment by seavan** [comment]
@Karim94 merged to dev

**Pull request merged**
