### PR TITLE
Feat open sans font

### PR DESCRIPTION
**Pull request by Karim94**
#### Relevant info and issue/PR links 
https://app.clubhouse.io/peerio/story/5481/mobile-fix-the-font
Notes:
1- iOS does not have fonts linked yet. Fonts are found in assets folder in root.
2- Need to do `npm install` to copy fonts to android
3- Action sheets do not have new fonts yet
#### Testing instructions  
Verify that new font is being used everywhere in the app. Labels, buttons, popups, text inputs, etc ... covering the general components means that, by extension, the entire app is covered. Nonetheless, I tested the entire app closely.

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by seavan** [comment]
iOS handles fonts quite differently.

bold, semibold and italic should be specified via fontWeight and fontStyle in iOS

and fontFamily is "Open Sans" with space instead of "OpenSans"

I tried to accmomodate for that and not break android.

iOS works currently, attached is the screenshot.

please check that Android works. if it is, we can give it to design testing.

image

**Comment by seavan** [comment]
@Karim94 ^

**Comment by Karim94** [comment]
@seavan works on Android, line which removes the space between 'Open Sans' needs to be kept in order to work.

**Comment by seavan** [comment]
@Karim94

please resolve conflicts

currently if the font is not found or there's a bad combination of flags, text crashes with exception.

to play it safer (there are a lot of changed files), please do the following:

introduce renderThrow() method
in render, call try { renderThrow() } catch { render normal ntext with props and styles applied from this.props. }

and the last thing:

don't introduce fontFamily to ghost source files, they are irrelevant at the moment.

**Comment by Karim94** [comment]
@seavan 
What causes the font to not be found? And what is a bad combination of flags? Like semibold and bold?

**Comment by seavan** [comment]
I don't want the app to crash if the font is not working. I want it to spam errors with console.error, but still work.

App will crash if the font is not in the bundle or it is not linked properly. Shouldn't do that, should degrade gracefully.

**Comment by seavan** [comment]
```
seavan@mbpro2016 peerio-mobile $ ./scripts/find-rn-text.sh
app/components/signup/signup-contact-sync-start.js:import { Text, View, Image } from 'react-native';
app/components/signup/signup-contact-add.js:import { Text, View, FlatList } from 'react-native';
app/components/signup/signup-contact-invite.js:import { Text, View, FlatList } from 'react-native';
app/components/contacts/contact-import-item.js:import { View, Text } from 'react-native';
app/components/ghosts/ghost-compose.js:import { View, Text, TextInput, TouchableOpacity } from 'react-native';
app/components/ghosts/ghost-view.js:import { View, Text, ScrollView, TouchableOpacity } from 'react-native';
app/components/ghosts/ghosts-zero-state.js:import { View, Text, Dimensions, Image } from 'react-native';
app/components/ghosts/ghost-item.js:import { View, Text, TouchableOpacity } from 'react-native';
app/components/shared/safe-component.js:import { Text } from 'react-native';
app/components/controls/search-bar.js:import { View, Text, TouchableOpacity, TextInput, Platform } from 'react-native';
```

**Comment by seavan** [comment]
@Karim94 some files from merge use rn text, you can use  ./scripts/find-rn-text.sh to check

**Pull request merged**
