### PR TITLE
Feat recent files chat

### PR DESCRIPTION
**Pull request by Karim94**
### Relevant info and issue/PR links 
https://app.clubhouse.io/peerio/story/2261/mobile-recent-files-list-in-chat-info-panel
The transition from `chat info` to a file (through the action sheet in recent files list) feels a bit clunky. Not sure what can be done about that, if anything needs to be done.
Important refactor:
Changed `files-action-sheet.js` to `file-upload-action-sheet.js`
Added new file: `file-action-sheet.js`
### Testing instructions  
The UI to be tested is the chat info view (for both, DM's and Channels)
#### Testing DM info:
We only have 1 variable which affects the layout of this UI, which is whether there are Recent Files in the current chat or not.
There are some issues with Recent Files right now, so its up to you @seavan and @ebilg if we want to release with the following issues:
1- Recent Files order is messed up (SDK / Server issue which we tried to investigate but there wasn't much can be done right now. I've added a CH task to revisit this after new File System is released)
2- Recent Files List UI does not update when a file is deleted from the Recent Files List using the action sheet (closing the Chat Info modal and opening it again refreshes the list)
3- If you delete all files from the Recent Files List, it will still think there are files there, but it won't show any file items, it will only show the header with an empty list. This is because SDK sends client the ID's of the recent files, we use the ID's to look up the files, but they're deleted, so we can't display anything. The header only hides when it receives nothing from SDK.

#### Testing Channel info:
We have 3 variables which change the layout of the UI:
1. Whether the User is a channel admin or regular member
2. If there are Users invited to the channel (which have not accepted or declined yet) 
3. If there are any Recent Files in the channel

This means we have 8 combinations of test cases where we have to make sure the UI matches the mocks (or in the cases where mocks might be missing, the UI is logical, fluid, reasonable, etc...) :
1. User is Admin, Channel does NOT have Invites, channel does NOT have Recent Files
2. User is Admin, Channel does NOT have Invites, channel HAS Recent Files
3. User is Admin, Channel HAS pending invites, channel does NOT have Recent Files
4. User is Admin, Channel HAS pending invites, channel HAS Recent Files
5. User is NOT Admin, Channel does NOT have pending invites, channel does NOT have Recent Files
6. User is NOT Admin, Channel does NOT have pending invites, channel HAS Recent Files
7. User is NOT Admin, Channel HAS pending invites, channel does NOT have Recent Files
8. User is NOT Admin, Channel HAS pending invites, channel HAS Recent Files

Testing Tips:
An easy way to test this is to have 2 emulators/devices and 3 test users, the "Admin", the "Non-Admin", and the user who never accepts invites, "Pending Invites User".
- Create 4 Rooms, and using "Admin" user, invite "Non-Admin" user to all 4 Rooms and the "Pending Invites User" to 2 Rooms.
- Now cases 1,3,5,7 can be tested.
- Afterwards, send one or more files in each of the 4 Rooms.
- Now cases 2,4,6,8 can be tested.

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by alexandra-marin** [comment]
@Karim94 please provide testing instructions

**Comment by ebilg** [comment]
issues listed in CH

**Comment by alexandra-marin** [comment]
Room:
simulator screen shot - iphone 6s - 2018-02-22 at 16 47 25
simulator screen shot - iphone 6s - 2018-02-22 at 16 47 17

Chat:
simulator screen shot - iphone x - 2018-02-22 at 16 46 10
simulator screen shot - iphone x - 2018-02-22 at 16 45 56

Can't test action sheet.
simulator screen shot - iphone x - 2018-02-22 at 16 49 40

**Comment by Karim94** [comment]
@alexandra-marin how come the icons are working in some screenshots but not in others? Do you have the error logs?

**Comment by ebilg** [comment]
can be merged

**Pull request merged**
