### PR TITLE
Fix 2fa popup

### PR DESCRIPTION
**Pull request by Karim94**
#### Relevant info and issue/PR links 
https://app.clubhouse.io/peerio/story/9612/mobile-friendlier-2sv-prompt
https://github.com/PeerioTechnologies/peerio-icebear/pull/243
#### Testing instructions  
Check that 2sv matches mocks, including different screen sizes.

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by seavan** [comment]
@ebilg ^

**Comment by ebilg** [comment]
well, it matches the mocks but you can't enter a code, tapping the dialog doesn't bring up keyboard
img_0806

**Comment by ebilg** [comment]
the entire code field is missing

**Comment by Karim94** [comment]
@ebilg fixed and tested on mac mini.

**Comment by ebilg** [comment]
commented on CH

**Comment by seavan** [comment]
@Karim94 always move bloated components into separate files.

I moved 2fa popup with input into separate file.

pretty sure problems you had with event handlers were becuse it was all written inline.

anyway, you don't even need a scrollview to achieve the requirements.

i will add animation of what I've done so far in the CH. if design accepts it, we'll just finish it. if not - you have a container to apply paddings/margins/transforms/animations whenever you want. you don't need to scrollview PopupLayout for that, I think/

**Comment by seavan** [comment]
@ebilg ready for testing.

**Comment by ebilg** [comment]
can be merged

**Pull request merged**
