### PR TITLE
Fix chat message alignment

### PR DESCRIPTION
**Pull request by Karim94**
#### Relevant info and issue/PR links 
https://app.clubhouse.io/peerio/story/3666/mobile-chat-message-alignment-is-off
#### Testing instructions  
Check that avatar.js didn't break every single correct thing about Peerio.

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Karim94** [comment]
@seavan removed scaleDim for that specific code. Refactoring avatar.js would help in fixing this a lot.

**Comment by seavan** [comment]
there are a lot of things in Avatar which use scale dim, so your fix would break things on other resolutions.
refactoring it would definitely help, but we'd have to redo all the markup, too, so that scaled dims would align proportionally.

so right now to fix this:

- fix scaledim so it always returns it's argument for now (no scaling)
- make sure the text is properly aligned right now

Then we'll be sure it won't break on myriad of iPhones and Androids.

**Comment by Karim94** [comment]
Works on 1440x2560 resolution screen (4.7") and on 640x1136 (4.0")

**Comment by seavan** [comment]
@alexandra-marin please check on iOS too, if it's good, we'll merge and test on dev.

**Comment by Karim94** [comment]
@alexandra-marin Testing instructions: Just make sure that the spacings (paddings, margins, etc ...) are not broken on different resolutions.

**Comment by alexandra-marin** [comment]
iphone 6s 10.3
simulator screen shot - iphone 6s - 2018-02-22 at 16 20 35

iphone x 11.2
simulator screen shot - iphone x - 2018-02-22 at 16 22 45

**Comment by seavan** [comment]
@Karim94 seems like it's off by a few pixels

**Comment by Karim94** [comment]
I pushed it a few more pixels @seavan @alexandra-marin

**Pull request merged**
