### PR TITLE
feat: allowed delete in inline files and images [branch ch4386]

### PR DESCRIPTION
**Pull request by Karim94**
#### Relevant info and issue/PR links 
https://app.clubhouse.io/peerio/story/4386/mobile-add-delete-file-to-inline-files-actions-like-in-desktop
#### Testing instructions  
1- Please test for inline files and images (two separate but similar looking action sheets are used)
2- Please note, inline file/image delete is only shown when the file exists in the user's fileStore. This is done because I encountered an instance where I tried deleting without the file existing in the user's fileStore and ran into an error. I then disabled the inline delete button when the file does not exist in fileStore, but haven't been able to reproduce the bug described above. Please try to reproduce a situation where an inline file is not in fileStore, and verify that the delete button is not shown in the action sheet. If you run into a situation where the delete button is shown but crashes or doesn't work as intended, it means the fix did not work and something else is causing the bug.

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ebilg** [comment]
does not work on iOS

**Comment by Karim94** [comment]
@seavan @ebilg 
Used the new action sheet to implement this. Should work now on iOS.
Let's wait for Samvel to look at the code before moving it for testing.
@alexandra-marin you dont need to take any action here, but feel free to review and test it.

**Comment by alexandra-marin** [comment]
@Karim94 spreadsheet works ok, but if I try to delete the popup doesn't disappear and can't click the buttons
Tested on ios 10.3
simulator screen shot - iphone 6s - 2018-05-03 at 15 32 12

**Comment by Karim94** [comment]
@alexandra-marin what were the errors in console?

**Comment by seavan** [comment]
@alexandra-marin @Karim94 ios overlay bug fixed, some error messages got fixed too.

Please, don't leave tasks hanging. There's no interaction between you two here for 6 days. who checks 

@ebilg should be ready for testing on a branch again.

**Comment by ebilg** [comment]
looks good

**Comment by seavan** [comment]
@Karim94 see   5:1  error  'react-native' import is restricted from being used. Do not use react-native Text, use custom-text instead  no-restricted-imports in test run

**Comment by Karim94** [comment]
@seavan fixed

**Comment by seavan** [comment]
this was merged from new actionsheets in newfs.

**Comment by seavan** [comment]
@Karim94 please delete the branch if there's no useful code there.

**Pull request closed without merging**
