### PR TITLE
feat: redesign of file view, inline file download

### PR DESCRIPTION
**Pull request by suprko**
#### Relevant info and issue/PR links 
https://app.clubhouse.io/peerio/story/302/mobile-new-file-details-view-and-unable-to-cancel-downloads
https://github.com/PeerioTechnologies/peerio-icebear/pull/181

#### Testing instructions  
Files view
* new menu icon to the right of each file: check that all actions are working

File details view (from Files view, tap on an individual file)
* completely redesigned
* check that download/cancel/open actions work in the main view
* new menu icon in top right; check that all actions are working

Inline files in chat (non-image files only)
* check that new download/cancel/open actions work in the new grey button below the file name
* some modifications to the menu icon in the right; check that menu actions are working

**Note**: in all cases, the "open" action attempts to open the file in the device's image viewer, even if the file is not an image. This was true for me on the emulator, as well as on my phone (Android) using prod. Karim reproduced on his Android phone. If this behaviour can be confirmed, then we should log it but as a separate bug (out of scope for this feature).

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by suprko** [comment]
@seavan 
In the original version of this task, the inline file action sheet needed to be different from the file view action sheet, so I created file-view-action-sheet.js. However, now they appear to have the same actions... The two action sheets are juuuust different enough that it would be kind of annoying to consolidate them. I'm going to ask design if we anticipate needing separate action sheets; if we don't, should I combine them now, or do that as a separate task?

**Comment by seavan** [comment]
@suprko yeah combining them now is fine!

**Comment by suprko** [comment]
@seavan Saumya says to keep them separate because action sheets are in the midst of redesign and they may be different in the future. ¯\_(ツ)_/¯

**Comment by seavan** [comment]
ok. is it ready for review, @suprko ?

**Comment by suprko** [comment]
@seavan yup ready

**Comment by ebilg** [comment]
can be merged

**Pull request merged**
